### PR TITLE
[impl] Add color api

### PR DESCRIPTION
**Pull request by m4b**
ref #4 

Adds color

screenshot from 2017-07-25 22-27-24

The api is pretty simpl; it takes a `(termion::Rgb, Range<usize>)` in the builder.

It might be a better idea to switch to the `term` crate for more robustness, but I don't have the energy.

### CODE REVIEW

**Comment by tmoers** [comment]
Wow, great! I have a holiday coming soon, so I'll try to migrate to term. Do you need a new version on crates.io already in the mean time?

**Comment by tmoers** [comment]
Hmm. It seems we'll certainly have to switch to term or put this behind an optional feature, because it no longer compiles on windows now.

Seems I'll also have to add appveyor support :)

**Comment by m4b** [comment]
Let's switch to term. I'll see if I can add it. Yea I'd want a new crates io when it's done, ideally

**Comment by m4b** [comment]
Wow, printing color cross platform in rust (and probably everything else) completely sucks.

Not to mention there's like 5 different libraries all doing the same thing but differently.

I think we should use termcolor from ripgrep, but the api, **cough**, isn't really that great at all.

I thought it would take care of automatically detecting if the output stream was a tty or not (and disable color) since it basically forces you to use a `BufferWriter` and print (and not return a string, which makes sense for windows afaik), but no, it does not do this at all.

Which at that point, like honestly why - why am I forced to check this, since it already requires printing to a stdout stream in the first place?

Anyway, I'm done randomly ranting ;)

So, problem as I see it is that `HexView` implements Display; this is ultimately problematic because for windows, afaics, color is inherently bound to the terminal/output object, so "coloring" the Display string doesn't make much sense.  I am probably oversimplifying but I think this is the gist; corrections of my paltry knowledge of windows color apis welcome :)

Anyway, I think it's workable; we probably can find a solution to reuse the display logic code, and enable printing color when appropriate, but it might be a little tricky, or ugly, or hacky, or perhaps all of the above.

How attached are you to the internal implementation being "beautiful"?  Specifically, might be able to reuse large parts of display logic with some basic macros, as the path of least resistance, but macros make code hard to read and ugly imho (and I'm very much guilty of using them).

I can also push some basic prototype, but it's basically me floundering with the termcolor api and trying to make stuff fit where it shouldn't/not understanding things.

**Comment by m4b** [comment]
@tmoers could you review at your leisure please?

So I tried  best to reuse display logic and also allow printing colors cross platform.

Basically adds a new method `print`, which prints cross-platform coloring, and also detects when it's piped, etc.

I added docs, and also a color module.

The color module basically reexports ColorSpec and Color from `termcolor` and provides convience functions for creating bold and non-bold colors, because the ColorSpec builder is pretty heavy hitting and inconvient imho.

Anyway, let me know what you think; I won't be able to work much more on this, as it's starting to get out of control :laughing:, but I do like the API in general.

Also, I'm not sure how to fix that single test failure?

**Comment by tmoers** [comment]
First of all, thanks a lot for your work!

A question though. When I try it locally, I get the same error as the travis build:
   https://travis-ci.org/tmoers/hexplay/jobs/261398842
Any idea?

**Comment by m4b** [comment]
:/ sorry I forgot to commit file and assumed CI failure was the test I mentioned, sorry about that...

**Comment by m4b** [comment]
@tmoers ping

I just fixed the test; it was a extra newline, from 2->3, dunno what else to do.

The other part was failing because of stupid typo with `gren`

I'd like to see this reviewed or merged soon, is that possible?

**Comment by tmoers** [comment]
I'll make some time this evening to do the merge. Thanks for all the work!

**Comment by m4b** [comment]
NP. Sorry for all the build errors initially :/

**Pull request merged**
